name: scientific_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*
  - cartopy=0.22.0
  - geopandas=0.14.2
  - matplotlib=3.8.2
  - numpy=1.26.4
  - pandas=2.1.3
  - scipy=1.12.0
  - statsmodels=0.14.1
  - scikit-learn=1.4.2
  - pip
  - pip:
    - seaborn